<?php
/**
 * PersonalizationParametersDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Storefront API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: storefront-v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\Storefront\Model;

use \ArrayAccess;
use \Aurigma\Storefront\ObjectSerializer;

/**
 * PersonalizationParametersDto Class Doc Comment
 *
 * @category Class
 * @description DTO class, containing information needed to start personalization process.
 * @package  Aurigma\Storefront
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PersonalizationParametersDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PersonalizationParametersDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'product_type' => '\Aurigma\Storefront\Model\ProductType',
        'id' => 'int',
        'version_id' => 'int',
        'api_gateway_url' => 'string',
        'design_editor_url' => 'string',
        'preflight_url' => 'string',
        'dynamic_image_url' => 'string',
        'ui_framework_url' => 'string',
        'simple_editor_url' => 'string',
        'workflow_elements_url' => 'string',
        'workflow_type' => '\Aurigma\Storefront\Model\WorkflowType',
        'workflow_content' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'product_type' => null,
        'id' => 'int32',
        'version_id' => 'int32',
        'api_gateway_url' => null,
        'design_editor_url' => null,
        'preflight_url' => null,
        'dynamic_image_url' => null,
        'ui_framework_url' => null,
        'simple_editor_url' => null,
        'workflow_elements_url' => null,
        'workflow_type' => null,
        'workflow_content' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'product_type' => false,
        'id' => true,
        'version_id' => true,
        'api_gateway_url' => true,
        'design_editor_url' => true,
        'preflight_url' => true,
        'dynamic_image_url' => true,
        'ui_framework_url' => true,
        'simple_editor_url' => true,
        'workflow_elements_url' => true,
        'workflow_type' => false,
        'workflow_content' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'product_type' => 'productType',
        'id' => 'id',
        'version_id' => 'versionId',
        'api_gateway_url' => 'apiGatewayUrl',
        'design_editor_url' => 'designEditorUrl',
        'preflight_url' => 'preflightUrl',
        'dynamic_image_url' => 'dynamicImageUrl',
        'ui_framework_url' => 'uiFrameworkUrl',
        'simple_editor_url' => 'simpleEditorUrl',
        'workflow_elements_url' => 'workflowElementsUrl',
        'workflow_type' => 'workflowType',
        'workflow_content' => 'workflowContent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'product_type' => 'setProductType',
        'id' => 'setId',
        'version_id' => 'setVersionId',
        'api_gateway_url' => 'setApiGatewayUrl',
        'design_editor_url' => 'setDesignEditorUrl',
        'preflight_url' => 'setPreflightUrl',
        'dynamic_image_url' => 'setDynamicImageUrl',
        'ui_framework_url' => 'setUiFrameworkUrl',
        'simple_editor_url' => 'setSimpleEditorUrl',
        'workflow_elements_url' => 'setWorkflowElementsUrl',
        'workflow_type' => 'setWorkflowType',
        'workflow_content' => 'setWorkflowContent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'product_type' => 'getProductType',
        'id' => 'getId',
        'version_id' => 'getVersionId',
        'api_gateway_url' => 'getApiGatewayUrl',
        'design_editor_url' => 'getDesignEditorUrl',
        'preflight_url' => 'getPreflightUrl',
        'dynamic_image_url' => 'getDynamicImageUrl',
        'ui_framework_url' => 'getUiFrameworkUrl',
        'simple_editor_url' => 'getSimpleEditorUrl',
        'workflow_elements_url' => 'getWorkflowElementsUrl',
        'workflow_type' => 'getWorkflowType',
        'workflow_content' => 'getWorkflowContent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('product_type', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('version_id', $data ?? [], null);
        $this->setIfExists('api_gateway_url', $data ?? [], null);
        $this->setIfExists('design_editor_url', $data ?? [], null);
        $this->setIfExists('preflight_url', $data ?? [], null);
        $this->setIfExists('dynamic_image_url', $data ?? [], null);
        $this->setIfExists('ui_framework_url', $data ?? [], null);
        $this->setIfExists('simple_editor_url', $data ?? [], null);
        $this->setIfExists('workflow_elements_url', $data ?? [], null);
        $this->setIfExists('workflow_type', $data ?? [], null);
        $this->setIfExists('workflow_content', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets product_type
     *
     * @return \Aurigma\Storefront\Model\ProductType|null
     */
    public function getProductType()
    {
        return $this->container['product_type'];
    }

    /**
     * Sets product_type
     *
     * @param \Aurigma\Storefront\Model\ProductType|null $product_type Customer's Canvas product type.
     *
     * @return self
     */
    public function setProductType($product_type)
    {
        if (is_null($product_type)) {
            throw new \InvalidArgumentException('non-nullable product_type cannot be null');
        }
        $this->container['product_type'] = $product_type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id Customer's Canvas product identifier.  May keep reference to `Product`, `Product Specification`, `Product Link` or `Product Bundle` (depending on `Type` value).
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets version_id
     *
     * @return int|null
     */
    public function getVersionId()
    {
        return $this->container['version_id'];
    }

    /**
     * Sets version_id
     *
     * @param int|null $version_id Customer's Canvas product version identifier.  May keep reference to version of `Product`, `Product Link` or `Product Bundle` (depending on `Type` value).
     *
     * @return self
     */
    public function setVersionId($version_id)
    {
        if (is_null($version_id)) {
            array_push($this->openAPINullablesSetToNull, 'version_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('version_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['version_id'] = $version_id;

        return $this;
    }

    /**
     * Gets api_gateway_url
     *
     * @return string|null
     */
    public function getApiGatewayUrl()
    {
        return $this->container['api_gateway_url'];
    }

    /**
     * Sets api_gateway_url
     *
     * @param string|null $api_gateway_url API Gateway URL address.
     *
     * @return self
     */
    public function setApiGatewayUrl($api_gateway_url)
    {
        if (is_null($api_gateway_url)) {
            array_push($this->openAPINullablesSetToNull, 'api_gateway_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_gateway_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_gateway_url'] = $api_gateway_url;

        return $this;
    }

    /**
     * Gets design_editor_url
     *
     * @return string|null
     */
    public function getDesignEditorUrl()
    {
        return $this->container['design_editor_url'];
    }

    /**
     * Sets design_editor_url
     *
     * @param string|null $design_editor_url Design Editor application URL address.
     *
     * @return self
     */
    public function setDesignEditorUrl($design_editor_url)
    {
        if (is_null($design_editor_url)) {
            array_push($this->openAPINullablesSetToNull, 'design_editor_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('design_editor_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['design_editor_url'] = $design_editor_url;

        return $this;
    }

    /**
     * Gets preflight_url
     *
     * @return string|null
     */
    public function getPreflightUrl()
    {
        return $this->container['preflight_url'];
    }

    /**
     * Sets preflight_url
     *
     * @param string|null $preflight_url Preflight application URL address.
     *
     * @return self
     */
    public function setPreflightUrl($preflight_url)
    {
        if (is_null($preflight_url)) {
            array_push($this->openAPINullablesSetToNull, 'preflight_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('preflight_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['preflight_url'] = $preflight_url;

        return $this;
    }

    /**
     * Gets dynamic_image_url
     *
     * @return string|null
     */
    public function getDynamicImageUrl()
    {
        return $this->container['dynamic_image_url'];
    }

    /**
     * Sets dynamic_image_url
     *
     * @param string|null $dynamic_image_url Dynamic Image application URL address.
     *
     * @return self
     */
    public function setDynamicImageUrl($dynamic_image_url)
    {
        if (is_null($dynamic_image_url)) {
            array_push($this->openAPINullablesSetToNull, 'dynamic_image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dynamic_image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dynamic_image_url'] = $dynamic_image_url;

        return $this;
    }

    /**
     * Gets ui_framework_url
     *
     * @return string|null
     */
    public function getUiFrameworkUrl()
    {
        return $this->container['ui_framework_url'];
    }

    /**
     * Sets ui_framework_url
     *
     * @param string|null $ui_framework_url Link to UI-Framework bundle.
     *
     * @return self
     */
    public function setUiFrameworkUrl($ui_framework_url)
    {
        if (is_null($ui_framework_url)) {
            array_push($this->openAPINullablesSetToNull, 'ui_framework_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ui_framework_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ui_framework_url'] = $ui_framework_url;

        return $this;
    }

    /**
     * Gets simple_editor_url
     *
     * @return string|null
     */
    public function getSimpleEditorUrl()
    {
        return $this->container['simple_editor_url'];
    }

    /**
     * Sets simple_editor_url
     *
     * @param string|null $simple_editor_url Link to Simple Editor bundle.
     *
     * @return self
     */
    public function setSimpleEditorUrl($simple_editor_url)
    {
        if (is_null($simple_editor_url)) {
            array_push($this->openAPINullablesSetToNull, 'simple_editor_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('simple_editor_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['simple_editor_url'] = $simple_editor_url;

        return $this;
    }

    /**
     * Gets workflow_elements_url
     *
     * @return string|null
     */
    public function getWorkflowElementsUrl()
    {
        return $this->container['workflow_elements_url'];
    }

    /**
     * Sets workflow_elements_url
     *
     * @param string|null $workflow_elements_url Link to Workflow Elements bundle.
     *
     * @return self
     */
    public function setWorkflowElementsUrl($workflow_elements_url)
    {
        if (is_null($workflow_elements_url)) {
            array_push($this->openAPINullablesSetToNull, 'workflow_elements_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('workflow_elements_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['workflow_elements_url'] = $workflow_elements_url;

        return $this;
    }

    /**
     * Gets workflow_type
     *
     * @return \Aurigma\Storefront\Model\WorkflowType|null
     */
    public function getWorkflowType()
    {
        return $this->container['workflow_type'];
    }

    /**
     * Sets workflow_type
     *
     * @param \Aurigma\Storefront\Model\WorkflowType|null $workflow_type Personalization workflow type.
     *
     * @return self
     */
    public function setWorkflowType($workflow_type)
    {
        if (is_null($workflow_type)) {
            throw new \InvalidArgumentException('non-nullable workflow_type cannot be null');
        }
        $this->container['workflow_type'] = $workflow_type;

        return $this;
    }

    /**
     * Gets workflow_content
     *
     * @return string|null
     */
    public function getWorkflowContent()
    {
        return $this->container['workflow_content'];
    }

    /**
     * Sets workflow_content
     *
     * @param string|null $workflow_content Serialized content of compiled personalization workflow.
     *
     * @return self
     */
    public function setWorkflowContent($workflow_content)
    {
        if (is_null($workflow_content)) {
            array_push($this->openAPINullablesSetToNull, 'workflow_content');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('workflow_content', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['workflow_content'] = $workflow_content;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


